### ISSUE TITLE
Openjk Jedi academy major lag on latest build at main menu

### ISSUE THREAD

**Issue by ravagers** [JACoders/OpenJK#984] opened 2018-07-29 01:19 UTC
Windows 10 using Intel graphics game and openjk was working 5 months ago perfectly 

**Is this for single player or multiplayer?**
Both

**Description of the bug (and if possible, steps to reproduce the bug):**
Major lag when updating to latest build at main menu and in-game 

**What did you expect to happen instead?**
Expected new build to work as I need it for certain new mods and as build that I used 5 months ago now fails to work instead it lags please help me

**Comment by ensiform** [comment] 2018-07-29 12:52
Nothing has changed in recent builds that would affect that.  Are you sure that you didn't upgrade from really old build?

**Comment by ravagers** [comment] 2018-07-29 14:29
"the opengl drivers for your graphics are not properly installed because of Windows?" 

What do you mean by this

**Comment by xycaleth** [comment] 2018-07-29 14:48
Can you copy and paste the contents of the console? You can run `/condump console.txt` which will create a file called `console.txt` in `Documents\Games\OpenJK` with the contents of the console.

**Comment by ravagers** [comment] 2018-07-29 15:07
heres the dump console.txt

OpenJK: v1.0.1.1 win_msvc-x86 Apr  2 2018
Initialising zone memory .....
----- FS_Startup -----
Current search path:
C:\Users\luke\Documents\My Games\OpenJK\base
C:\Program Files (x86)\Lucasarts\Star Wars Jedi Knight Jedi
Academy\GameData\base\assets3.pk3 (16 files)
C:\Program Files (x86)\Lucasarts\Star Wars Jedi Knight Jedi
Academy\GameData\base\assets2.pk3 (62 files)
C:\Program Files (x86)\Lucasarts\Star Wars Jedi Knight Jedi
Academy\GameData\base\assets1.pk3 (8320 files)
C:\Program Files (x86)\Lucasarts\Star Wars Jedi Knight Jedi
Academy\GameData\base\assets0.pk3 (15346 files)
C:\Program Files (x86)\Lucasarts\Star Wars Jedi Knight Jedi
Academy\GameData\base

----------------------
23744 files in pk3 files
execing default.cfg
execing openjk_sp.cfg
couldn't exec autoexec_sp.cfg
Running Jedi Academy Mode
----- Client Initialization -----
----- Initializing Renderer ----
Trying to load "rdsp-vanilla_x86.dll" from "C:\Program Files
(x86)\Lucasarts\Star Wars Jedi Knight Jedi Academy\GameData"...
-------------------------------
----- Client Initialization Complete -----
--- Common Initialization Complete ---
SDL Version Compiled: 2.0.8
SDL Version Linked: 2.0.8
SDL using driver "windows"
Initializing display
Display aspect: 1.779
...setting mode -1: 1600 1024
Using 24 color bits, 24 depth, 8 stencil display.
WARNING: Couldn't get window display mode, no resolutions detected (Couldn't
find display mode match).
...ERROR: no display modes could be found.
Setting r_mode -1 failed, falling back on r_mode 4
Initializing display
Display aspect: 1.779
...setting mode 4: 800 600
Using 24 color bits, 24 depth, 8 stencil display.
Available modes: '1280x720 1366x768 1360x768 1280x768 320x200 640x400
1280x800 1280x600 320x240 400x300 512x384 640x480 800x600 1024x768 656x496'
Initializing OpenGL extensions
...no supported texture compression method found
.....ignoring texture compression
...GL_EXT_texture_env_add not found
...GL_EXT_texture_filter_anisotropic not found
...using GL_EXT_texture_edge_clamp
...GL_ARB_multitexture not found
...GL_EXT_compiled_vertex_array not found
...GL_NV_register_combiners not found
...GL_ARB_vertex_program not found
...GL_ARB_fragment_program not found

GL_VENDOR: Chain Studios (QeffectsGL 1.2)
GL_RENDERER: GDI Generic
GL_VERSION: 1.1.0
GL_WIN_swap_hint GL_EXT_bgra GL_EXT_paletted_texture
GL_MAX_TEXTURE_SIZE: 1024
GL_MAX_ACTIVE_TEXTURES_ARB: 0

PIXELFORMAT: color(24-bits) Z(24-bit) stencil(8-bits)
MODE: -1, 800 x 600 fullscreen hz:N/A
GAMMA: hardware w/ 0 overbright bits
rendering primitives: multiple glArrayElement
texturemode: GL_LINEAR_MIPMAP_LINEAR
picmip: 0
texture bits: 0
multitexture: disabled
compiled vertex arrays: disabled
texenv add: disabled
compressed textures: disabled
compressed lightmaps: disabled
texture compression method: None
anisotropic filtering: disabled  Dynamic Glow: disabled

------- sound initialization -------
SDL_Init( SDL_INIT_AUDIO )... OK
SDL audio driver is "wasapi".
SDL_AudioSpec:
  Format:   AUDIO_S16LSB
  Freq:     44100
  Samples:  1024
  Channels: 2
Starting SDL audio callback...
SDL audio initialized.
Extended sound quality field to contain very high option.
Extended subtitles field to contain all voiceovers option.
UI menu load time = 321 milli seconds
]condump console.txt
Dumped console text to console.txt.

**Comment by ensiform** [comment] 2018-07-29 18:20
Disable Qeffects first.  Cannot guarantee compatibility with a third party wrapper.

**Comment by ravagers** [comment] 2018-07-29 18:36
How do I disable qeffects

**Comment by ensiform** [comment] 2018-07-29 21:03
Remove or rename the dll that you placed in the gamedata folder

**Comment by ravagers** [comment] 2018-07-29 21:31
Yeah the DLLs are 
Eaxman.dll
Goggame-1428935726.dll
Ifc22.dll
Jagamex86.dll
Msvcp120.dll
Msvcr120.dll
Openal32.dll
Rdsp-vanilla_x86.dll
Rd-vanilla_x86.dll
Sdl2.dll

**Comment by ravagers** [comment] 2018-07-29 23:30
This is weird because I just tested kotf and it worked but vanilla game and md2 won't work .. also mb2 works

**Comment by ensiform** [comment] 2018-07-30 18:53
Well, it looks like you might have QEffects installed somewhere else then?  Probably in the system folder 😱

**Comment by ravagers** [comment] 2018-07-31 15:25
Where is the system folder ?

**Comment by ensiform** [comment] 2018-07-31 15:32
I can't recommend touching anything in the system32 folder because you will probably screw things up more.

You've installed it for some game and it is attempting to be used here too.  I can't help any further unless you find out what installed it and where it was placed.

**Comment by Razish** [comment] 2023-10-19 03:16
Closing as it appears to be caused by external software (QEffects). Please re-open if you're still having performance issues on a fresh install.

**Closed by Razish** 2023-10-19 03:16 UTC
