### ISSUE TITLE
White screen in SP at beginning of map loads prior to map load screen.

### ISSUE THREAD

**Issue by ensiform** [JACoders/OpenJK#602] opened 2015-01-01 21:40 UTC
There has always been a white screen shown at map loads in SP. 

Seems to be related to non 4:3 screen size.

Also happens at intro cinematic too in current codebase, might have fix for this locally.

![](http://i.imgur.com/STSLwo4.png)

**Comment by xycaleth** [comment] 2015-01-02 20:58
The issue caused by this code in client/cl_scrn.cpp:
```c++
	// wide aspect ratio screens need to have the sides cleared
	// unless they are displaying game renderings
	if ( uiFullscreen || (cls.state != CA_ACTIVE && cls.state != CA_CINEMATIC) ) {
		if ( cls.glconfig.vidWidth * 480 > cls.glconfig.vidHeight * 640 ) {
			re.SetColor( g_color_table[0] );
			re.DrawStretchPic( 0, 0, cls.glconfig.vidWidth, cls.glconfig.vidHeight, 0, 0, 0, 0, 0 );
			re.SetColor( NULL );
		}
	}```
Setting the colour to black (``g_color_table[0]``) doesn't work because the default shader isn't affected by colour.

**Comment by xycaleth** [comment] 2015-01-02 21:22
The code was necessary in Q3 because the main menus were a fixed aspect ratio. So the entire screen was cleared to black first (though why it doesn't clear to black now, I'm not sure) before drawing the menu to prevent a HOM effect.

As JKA menus take up the full screen, even in widescreen, the code is no longer necessary. I'll remove the code from SP and MP and close this issue.

**Closed** 2015-01-02 21:27 UTC
Labels: bug, MEDIUM PRIORITY, SP

**Comment by ensiform** [comment] 2015-10-17 03:45
I just noticed something interesting though... This used to call qhandle 0 in SP and properly used cls.whiteShader in MP which color does affect.
