### ISSUE TITLE
Mac and Linux makefiles output compiled files inside deep directory tree

### ISSUE THREAD

**Issue by TheInsaneSyko** [JACoders/OpenJK#744] opened 2015-11-01 01:01 UTC
After building OpenJK on Linux and Mac (I've tried both) the outputted files are in a deep maze of folders inside the folder with the executable.  For example, jagamex86_64.so is outputted in [build directory]/code/game/jagamex86_64.so while the executable is outputted in [build directory]. Starting the executable causes a render failure because the render library is not in the same folder as the executable. Shouldn't the compiled libraries be placed in the same folder as the executable so they can be launched without having to copy all of the libraries into one directory every time a code change is made?

**Comment by Razish** [comment] 2015-11-01 02:35
Did you run `make install`? With a valid `CMAKE_INSTALL_PREFIX` variable?

**Comment by ensiform** [comment] 2015-11-01 05:37
The libraries (with exception of renderer) cannot be launched right next to the executable as it is by design.

**Comment by Koncord** [comment] 2015-11-01 07:52
Copy all *.so to code/game/base.

**Comment by Razish** [comment] 2015-11-01 09:12
make's default target is not meant to be put the produced binaries in a file tree ready for JA, it's just meant to produce them.
`make install` is meant to gather them to an install directory, e.g. `/home/user/games/` named JediAcademy

**Comment by TheInsaneSyko** [comment] 2015-11-01 14:57
I used Cmake GUI. The CMAKE_INSTALL_PREFIX was set to /usr/local/, and  yes, I just ran make install and it installed the game to my /usr/local/ directory. I'm using Code blocks to compile however, and  and I don't want to have to run make install every time I build the program, any way to avoid this?

**Comment by shinyquagsire23** [comment] 2015-11-01 22:19
I've always just symlinked the files where I need them for testing. Works fine for me.

**Comment by Razish** [comment] 2015-11-24 03:35
`make install` is the only way this is going to work for the foreseeable future. symlinks are a great technique.

Closing as wontfix, working as intended. This isn't OpenJK-specific behaviour.

**Closed by Razish** 2015-11-24 03:35 UTC
Labels: Linux, question, Won't fix
