### ISSUE TITLE
Problem with accent

### ISSUE THREAD

**Issue by Yberion** [JACoders/OpenJK#669] opened 2015-05-17 09:14 UTC
Since SDL2 we can't use this accent ^, making "ê" will result in game to ^e.

**Comment by xycaleth** [comment] 2015-05-17 09:16
What keyboard layout are you using?

**Comment by xycaleth** [comment] 2015-05-17 09:29
Nevermind, I've managed to reproduce the problem. I'm assuming you're using a French AZERTY keyboard, and typing ^ and then e to get a ê :)

**Comment by xycaleth** [comment] 2015-05-17 09:36
This is a bug in SDL2 (https://bugzilla.libsdl.org/show_bug.cgi?id=2834) and looks like it will be fixed for SDL 2.0.4.

**Comment by Yberion** [comment] 2015-05-17 11:23
Ok good to hear, thanks for your answer :)

**Comment by ensiform** [comment] 2015-06-28 17:42
Fix was applied on June 25th to SDL2 Pending 2.0.4 release.

http://hg.libsdl.org/SDL/rev/02273530b7bf

**Comment by Yberion** [comment] 2015-06-29 19:17
Good, thank you

**Comment by mrwonko** [comment] 2016-03-25 16:32
We now use SDL 2.0.4 - is this fixed?

**Comment by ensiform** [comment] 2016-03-25 17:29
Should be

**Comment by mrwonko** [comment] 2016-03-25 17:45
Yup, works properly now.

**Closed by mrwonko** 2016-03-25 17:45 UTC
Labels: T - Bug, V- Externally Blocked
