### ISSUE TITLE
Cannot interact with things after loading

### ISSUE THREAD

**Issue by t-animal** [JACoders/OpenJK#889] opened 2016-11-04 19:51 UTC
I run a Arch 64bit and built the game as of commit d3f5b3b .

When I load the game after dying, I cannot interact with things as TheCherry pointed out in issue #780 . 
This is fixed by restarting the game. 

However even after restarting I still cannot interact with some switches and stuff that needs force power (e.g. the wall which has to be destroyed during the force power training in the beginning). This is NOT fixed by restarting the game but by restarting the mission.  Thus some levels effectively become permadeath levels - you cannot finish them after you've died once.

**Comment by ensiform** [comment] 2016-11-04 20:11
When was the last commit it worked.  This commit just disables an unused variable on JK2 MODE which doesn't change any functionality.

**Comment by t-animal** [comment] 2016-11-04 21:34
I don't know. I'm playing it for the first time. I could try and find out after I've finished it.

**Comment by t-animal** [comment] 2016-11-04 23:26
During the mission where you have to race on the hoverbikes I noticed that the final cutscene was not triggered after loading, too. Therefore the level could not be finished. I guess that issue is related.

**Comment by ensiform** [comment] 2016-11-05 00:18
Well the game runs good for me on mint 18 64 so that's strange.

**Comment by gabor-udvari** [comment] 2016-11-25 04:04
I experience the same issue on Ubuntu 16.04 (64 bit) with the pre-built binaries. Happens with openjk-2016-11-21-39baf07d and openjk-2016-10-31-d3f5b3bd. I hit these issues so far:
- if you die on yavin1b, after reloading Rosh will not open the first gate
- if you die on t1_surprise, after reloading you cannot force pull down the escalator at the sandcrawler
- if you die on t1_rail, after reloading you cannot switch off the electricity between the two trams.

Closing the game and restarting fixes these.

**Comment by Razish** [comment] 2016-11-25 08:34
Confirmed:
1. Start new game (I picked Jedi Master)
2. Die to the howlers before triggering the cutscene
3. "Load Checkpoint"
4. The howlers do nothing, can't trigger the cutscene/checkpoint
![dumb howlers](https://dl.dropbox.com/s/bhgz2n3ls3ecuzh/shot2016-11-25_18-38-27_c.jpg)

**Comment by xycaleth** [comment] 2016-11-26 18:06
Seems like a regression of #257 which I had fixed in e8fc63788. I recall bace05c9b potentially undid my fix but I couldn't remember what the visibility compile flag was for at the time.

**Comment by Razish** [comment] 2016-11-27 16:32
Perhaps we need a comment around the compiler switch so people know not to remove it :P

**Comment by gabor-udvari** [comment] 2016-12-27 22:34
I did some further testing and it seems that yavin1b is a special case. With the precompiled binary I can reproduce the bug on different maps. When I compile the binary from source the bug goes away on these maps (after dying and reloading checkpoint):
* t1_surprise: cannot force pull down the escalator at the sandcrawler
* t1_rail: cannot force pull down the escalator at the sandcrawler
* t3_rift: cannot force push the very first rock at the beginning

But the yavin1b issue still exists, even if all the above work. Putting the `-fvisibility=hidden` back to the CMakeLists.txt does not have any effect. The issue on yavin1b still exists while all the others are not. I compiled on Ubuntu 16.04, gcc version is 5.4.0 20160609.

**Comment by t-animal** [comment] 2016-12-27 23:11
That is weird because I install from AUR and therefore always compile from 
source and I experienced all the described bugs. I've finished the game now 
and will take a closer look.


Am 27. Dezember 2016 23:35:09 schrieb Gábor Udvari <notifications@github.com>:

**Comment by smcv** [comment] 2017-01-21 17:46
PR #905 was intended to fix #902, but might fix this as well (I tried yavin1b after a save/load cycle and it seems fine).

**Comment by t-animal** [comment] 2017-01-21 18:35
With the current HEAD the bug is fixed for me, too.

**Comment by smcv** [comment] 2017-01-21 20:12
Huh. Current `master` doesn't have my fix for #902 yet, so your bug must have been something different?

**Comment by gabor-udvari** [comment] 2017-01-22 15:50
PR #905 was merged since then, pulled master and compiled it, all my bugs are now fixed on Ubuntu 16.04 64bit. Thanks @smcv !

**Comment by smcv** [comment] 2017-01-22 18:09
Both people previously reporting problems here say they are now solved, so I think this issue can be closed?

**Closed** 2017-01-22 19:13 UTC

**Comment by manuLlanos** [comment] 2017-03-21 03:37
Hello, I'm running Debian stable 64 bits. And this issue keeps happening in singleplayer.
Each time I load a save after playing, it seems like the map triggers ( levers, dialogs, elevators) cease to work until the game is reloaded.
I have installed the latest Linux 64 bit version as of now (2017-03-20)
![loadingbug_linux64](https://cloud.githubusercontent.com/assets/26463463/24131590/49e7afc8-0dce-11e7-924a-6917dc731f19.png)
