### ISSUE TITLE
Make installation easier by providing readme or installer

### ISSUE THREAD

**Issue by sudge** [JACoders/OpenJK#639] opened 2015-03-09 09:58 UTC
Operating System:
whatever

SP/MP:
whatever

What the problem is:
Well, talking about people who are not such as IT specialist or something like that. Some of them really need included instruction about what to do with files in achve, I know there is instructions on github page, but people often just miss it. People dont know how to run the game as portable (configs in the game folder), they dont know how to make executable file to run some modification. So what about just a little instruction in txt file included in achive? Just write as "for stupid", some people really need it. Or maybe some *.bat of *.sh (depends on platform) to run the game in portable mode. Plus some people really looking for installer, they just use to things like that.

**Comment by xycaleth** [comment] 2015-03-09 10:26
As @Razish [already explained](https://github.com/JACoders/OpenJK/issues/638#issuecomment-77812310):
> This will all be handled with an official release and website, nothing to worry about here. Up until now it's mostly been preview builds that get frequently updated for people who are curious, so it was up to them to work out how to use the files. If they couldn't work that out, it's probably not suitable for them.

We're approaching our first 'official' release in a few weeks which will include a full installer so people can just double-click an icon and everything will happen automatically. We haven't done this yet as the builds that are available at the moment are just 'preview builds'.

**Comment by xycaleth** [comment] 2015-03-09 10:39
Thsi is also kind of a duplicate of #627...

**Comment by xycaleth** [comment] 2015-03-10 23:45
Some progress :)
![Installer](https://dl.dropboxusercontent.com/u/874909/Screenshots/installer.png)

**Comment by makson96** [comment] 2015-03-11 15:41
Hi,
If you look for easy installation guide on Ubuntu you can take a look at my project:
http://youtu.be/4pnSPCPRnKM

**Comment by xycaleth** [comment] 2018-05-05 21:13
Closing since this is a duplicate of #627.

**Closed by xycaleth** 2018-05-05 21:13 UTC
Labels: T - Documentation, T - Enhancement, V - Duplicate
